# TX_CHANNELS is rewritten at startup by entrypoint.sh.
pcm.inferno {
    type inferno
    NAME "Dante-Pi"
    TX_CHANNELS 8
    RX_CHANNELS 0
    SAMPLE_RATE 48000
    TX_LATENCY_NS 10000000
    CLOCK_PATH "/tmp/usrvclock"
    hint {
        show on
        description "Inferno Dante 8-Channel Soundcard"
    }
}

ctl.inferno {
    type inferno
}

pcm.!default {
    type plug
    slave.pcm "inferno"
}
