package config

func GetDefaultPresets() []StationPreset {
	return []StationPreset{
		{
			ID:          "dr-p3",
			Name:        "DR P3",
			Category:    "Danish Public Radio",
			StreamURL:   "https://drstream.akamaized.net/live/p3/s/p3_hls.m3u8",
			LogoURL:     "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/radio.png",
			Description: "Danmarks største ungdoms- og musikkanal - Hits, ny musik & underholdning",
			Bitrate:     "192 kbps",
			IsCustom:    false,
		},
		{
			ID:          "dr-p1",
			Name:        "DR P1",
			Category:    "Danish Public Radio",
			StreamURL:   "https://drstream.akamaized.net/live/p1/s/p1_hls.m3u8",
			LogoURL:     "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/radio.png",
			Description: "Nyheder, debat, samfund og kultur fra Danmarks Radio",
			Bitrate:     "192 kbps",
			IsCustom:    false,
		},
		{
			ID:          "dr-p2",
			Name:        "DR P2 Klassisk",
			Category:    "Danish Public Radio",
			StreamURL:   "https://drstream.akamaized.net/live/p2/s/p2_hls.m3u8",
			LogoURL:     "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/radio.png",
			Description: "Klassisk musik, koncerter og opera",
			Bitrate:     "192 kbps",
			IsCustom:    false,
		},
		{
			ID:          "dr-p4-kbh",
			Name:        "DR P4 København",
			Category:    "Danish Public Radio",
			StreamURL:   "https://drstream.akamaized.net/live/p4kbh/s/p4kbh_hls.m3u8",
			LogoURL:     "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/radio.png",
			Description: "Regionale nyheder og populær musik for Hovedstaden",
			Bitrate:     "192 kbps",
			IsCustom:    false,
		},
		{
			ID:          "dr-p4-fyn",
			Name:        "DR P4 Fyn",
			Category:    "Danish Public Radio",
			StreamURL:   "https://drstream.akamaized.net/live/p4fyn/s/p4fyn_hls.m3u8",
			LogoURL:     "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/radio.png",
			Description: "Regionale nyheder og musik for Fyn og øerne",
			Bitrate:     "192 kbps",
			IsCustom:    false,
		},
		{
			ID:          "dr-p4-aarhus",
			Name:        "DR P4 Østjylland",
			Category:    "Danish Public Radio",
			StreamURL:   "https://drstream.akamaized.net/live/p4aar/s/p4aar_hls.m3u8",
			LogoURL:     "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/radio.png",
			Description: "Regionale nyheder og musik for Østjylland",
			Bitrate:     "192 kbps",
			IsCustom:    false,
		},
		{
			ID:          "dr-p5",
			Name:        "DR P5",
			Category:    "Danish Public Radio",
			StreamURL:   "https://drstream.akamaized.net/live/p5/s/p5_hls.m3u8",
			LogoURL:     "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/radio.png",
			Description: "Klassiske hits fra de seneste 6 årtier og hyggelig radio",
			Bitrate:     "192 kbps",
			IsCustom:    false,
		},
		{
			ID:          "dr-p6-beat",
			Name:        "DR P6 Beat",
			Category:    "Danish Public Radio",
			StreamURL:   "https://drstream.akamaized.net/live/p6b/s/p6b_hls.m3u8",
			LogoURL:     "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/radio.png",
			Description: "Alternativ musik, indie, rock og nyskabende toner",
			Bitrate:     "192 kbps",
			IsCustom:    false,
		},
		{
			ID:          "dr-p8-jazz",
			Name:        "DR P8 Jazz",
			Category:    "Danish Public Radio",
			StreamURL:   "https://drstream.akamaized.net/live/p8j/s/p8j_hls.m3u8",
			LogoURL:     "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/radio.png",
			Description: "Jazz i alle afskygninger - moderne og klassisk",
			Bitrate:     "192 kbps",
			IsCustom:    false,
		},
		{
			ID:          "radio4-dk",
			Name:        "Radio4 Danmark",
			Category:    "News & Talk",
			StreamURL:   "https://netradio.radio4.dk/radio4",
			LogoURL:     "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/radio.png",
			Description: "Hele Danmarks taleradio - Nyheder og debat",
			Bitrate:     "128 kbps",
			IsCustom:    false,
		},
		{
			ID:          "nova-fm",
			Name:        "Nova FM",
			Category:    "Pop & Hits",
			StreamURL:   "https://stream.bauermedia.dk/nova128",
			LogoURL:     "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/radio.png",
			Description: "De største hits fra 90'erne, 00'erne og i dag",
			Bitrate:     "128 kbps",
			IsCustom:    false,
		},
		{
			ID:          "the-voice-dk",
			Name:        "The Voice",
			Category:    "Pop & Hits",
			StreamURL:   "https://stream.bauermedia.dk/voice128",
			LogoURL:     "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/radio.png",
			Description: "Danmarks Hitstation - Det nyeste og hotteste musik",
			Bitrate:     "128 kbps",
			IsCustom:    false,
		},
		{
			ID:          "pop-fm",
			Name:        "Pop FM",
			Category:    "Pop & Hits",
			StreamURL:   "https://stream.bauermedia.dk/pop128",
			LogoURL:     "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/radio.png",
			Description: "De største popklassikere fra 70'erne, 80'erne og 90'erne",
			Bitrate:     "128 kbps",
			IsCustom:    false,
		},
		{
			ID:          "myrock-dk",
			Name:        "myROCK",
			Category:    "Rock & Alternative",
			StreamURL:   "https://stream.bauermedia.dk/myrock128",
			LogoURL:     "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/radio.png",
			Description: "Danmarks Rockstation - Klassisk rock og heavy metal",
			Bitrate:     "128 kbps",
			IsCustom:    false,
		},
		{
			ID:          "bbc-radio-1",
			Name:        "BBC Radio 1",
			Category:    "International",
			StreamURL:   "https://stream.live.vc.bbcmedia.co.uk/bbc_radio_one",
			LogoURL:     "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/radio.png",
			Description: "The best in current pop, dance and youth culture from UK",
			Bitrate:     "128 kbps",
			IsCustom:    false,
		},
		{
			ID:          "bbc-radio-6",
			Name:        "BBC Radio 6 Music",
			Category:    "International",
			StreamURL:   "https://stream.live.vc.bbcmedia.co.uk/bbc_6music",
			LogoURL:     "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/radio.png",
			Description: "Alternative music, curated shows and indie sounds",
			Bitrate:     "128 kbps",
			IsCustom:    false,
		},
		{
			ID:          "somafm-groovesalad",
			Name:        "SomaFM: Groove Salad",
			Category:    "Ambient & Chillout",
			StreamURL:   "https://ice6.somafm.com/groovesalad-256-mp3",
			LogoURL:     "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/radio.png",
			Description: "A nicely chilled plate of ambient/downtempo beats and grooves",
			Bitrate:     "256 kbps",
			IsCustom:    false,
		},
		{
			ID:          "kexp-seattle",
			Name:        "KEXP 90.3 FM Seattle",
			Category:    "Rock & Alternative",
			StreamURL:   "https://kexp.streamguys1.com/kexp160.aac",
			LogoURL:     "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/radio.png",
			Description: "Where the music matters - Independent music curation",
			Bitrate:     "160 kbps AAC",
			IsCustom:    false,
		},
	}
}
